# Generated by Django 5.2 on 2025-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CR', 'CURD'), ('IC', 'ICE-CREAMS'), ('GH', 'GHEE'), ('CZ', 'CHEESE'), ('LS', 'LASSI'), ('PN', 'PANEER'), ('MS', 'MILK SHAKE'), ('ML', 'MILK')], max_length=200)),
                ('product_image', models.ImageField(upload_to='product')),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
            ],
        ),
    ]
