# Generated by Django 5.0.2 on 2025-05-04 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Gujranwala', 'Gujranwala'), ('Gujrat', 'Gujrat'), ('Sialkot', 'Sialkot'), ('Sukkur', 'Sukkur'), ('Hyderabad', 'Hyderabad'), ('Nawabshah', 'Nawabshah'), ('Mirpurkhas', 'Mirpurkhas'), ('Nawabshah', 'Nawabshah'), ('Mirpurkhas', 'Mirpurkhas'), ('Nawabshah', 'Nawabshah'), ('Mirpurkhas', 'Mirpurkhas'), ('Nawabshah', 'Nawabshah'), ('Mirpurkhas', 'Mirpurkhas'), ('Nawabshah', 'Nawabshah'), ('Mirpurkhas', 'Mirpurkhas'), ('Nawabshah', 'Nawabshah'), ('Mirpurkhas', 'Mirpurkhas'), ('Nawabshah', 'Nawabshah'), ('Mirpurkhas', 'Mirpurkhas')], max_length=200)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
